data "aws_iam_policy_document" "cur_kms" {
  #checkov:skip=CKV_AWS_109:KMS key policy: "*" is the key itself, and the account root statement is the AWS default that keeps the key manageable.
  #checkov:skip=CKV_AWS_111:KMS key policy: "*" is the key itself, and the account root statement is the AWS default that keeps the key manageable.
  #checkov:skip=CKV_AWS_356:KMS key policy: "*" is the key itself; key policies can't name a narrower resource.
  count = local.create_cur_export ? 1 : 0

  statement {
    sid       = "EnableAccountAdministration"
    effect    = "Allow"
    actions   = ["kms:*"]
    resources = ["*"]

    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::${local.account_id}:root"]
    }
  }

  statement {
    sid    = "AllowDataExportEncryption"
    effect = "Allow"
    actions = [
      "kms:Decrypt",
      "kms:Encrypt",
      "kms:GenerateDataKey*",
      "kms:DescribeKey",
    ]
    resources = ["*"]

    principals {
      type        = "Service"
      identifiers = ["bcm-data-exports.amazonaws.com", "billingreports.amazonaws.com"]
    }

    condition {
      test     = "StringEquals"
      variable = "aws:SourceAccount"
      values   = [local.account_id]
    }
  }

  statement {
    sid       = "AllowSpikeDecrypt"
    effect    = "Allow"
    actions   = ["kms:Decrypt", "kms:DescribeKey"]
    resources = ["*"]

    principals {
      type        = "AWS"
      identifiers = [local.spike_cur_reader_arn]
    }
  }
}

resource "aws_kms_key" "cur" {
  count = local.create_cur_export ? 1 : 0

  region                  = local.home_region
  description             = "Encrypts the Directeam CUR 2.0 bucket"
  enable_key_rotation     = true
  deletion_window_in_days = 30
  policy                  = data.aws_iam_policy_document.cur_kms[0].json
  tags                    = local.tags
}

resource "aws_kms_alias" "cur" {
  count = local.create_cur_export ? 1 : 0

  region        = local.home_region
  name          = "alias/directeam-finops-cur-${local.account_id}"
  target_key_id = aws_kms_key.cur[0].key_id
}

resource "aws_s3_bucket" "cur" {
  #checkov:skip=CKV_AWS_18:Only AWS Data Exports writes and Spike reads; access logging would add a log bucket in the customer account.
  #checkov:skip=CKV_AWS_144:The export can be regenerated by AWS Data Exports, so cross-region replication only doubles the cost.
  #checkov:skip=CKV2_AWS_62:Spike reads the export on a schedule; no event notifications are consumed.
  count = local.create_cur_export ? 1 : 0

  region        = local.home_region
  bucket        = local.cur_bucket_name
  force_destroy = var.cur_bucket_force_destroy
  tags          = local.tags
}

resource "aws_s3_bucket_versioning" "cur" {
  count = local.create_cur_export ? 1 : 0

  region = local.home_region
  bucket = aws_s3_bucket.cur[0].id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_ownership_controls" "cur" {
  count = local.create_cur_export ? 1 : 0

  region = local.home_region
  bucket = aws_s3_bucket.cur[0].id

  rule {
    object_ownership = "BucketOwnerEnforced"
  }
}

resource "aws_s3_bucket_public_access_block" "cur" {
  count = local.create_cur_export ? 1 : 0

  region                  = local.home_region
  bucket                  = aws_s3_bucket.cur[0].id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "cur" {
  count = local.create_cur_export ? 1 : 0

  region = local.home_region
  bucket = aws_s3_bucket.cur[0].id

  rule {
    bucket_key_enabled = true

    apply_server_side_encryption_by_default {
      kms_master_key_id = aws_kms_key.cur[0].arn
      sse_algorithm     = "aws:kms"
    }
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "cur" {
  count = local.create_cur_export ? 1 : 0

  region = local.home_region
  bucket = aws_s3_bucket.cur[0].id

  rule {
    id     = "ManageReportVersions"
    status = "Enabled"

    filter {}

    noncurrent_version_expiration {
      noncurrent_days = 90
    }

    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }

  depends_on = [aws_s3_bucket_versioning.cur]
}

data "aws_iam_policy_document" "cur_bucket" {
  count = local.create_cur_export ? 1 : 0

  statement {
    sid       = "AllowSpikeListBucket"
    effect    = "Allow"
    actions   = ["s3:ListBucket", "s3:GetBucketLocation"]
    resources = [aws_s3_bucket.cur[0].arn]

    principals {
      type        = "AWS"
      identifiers = [local.spike_cur_reader_arn]
    }
  }

  statement {
    sid       = "AllowSpikeReadObjects"
    effect    = "Allow"
    actions   = ["s3:GetObject", "s3:GetObjectVersion"]
    resources = ["${aws_s3_bucket.cur[0].arn}/*"]

    principals {
      type        = "AWS"
      identifiers = [local.spike_cur_reader_arn]
    }
  }

  statement {
    sid       = "DenyNonHTTPSAccess"
    effect    = "Deny"
    actions   = ["s3:*"]
    resources = [aws_s3_bucket.cur[0].arn, "${aws_s3_bucket.cur[0].arn}/*"]

    principals {
      type        = "*"
      identifiers = ["*"]
    }

    condition {
      test     = "Bool"
      variable = "aws:SecureTransport"
      values   = ["false"]
    }
  }

  statement {
    sid       = "AllowDataExportsDelivery"
    effect    = "Allow"
    actions   = ["s3:PutObject", "s3:GetBucketPolicy"]
    resources = [aws_s3_bucket.cur[0].arn, "${aws_s3_bucket.cur[0].arn}/*"]

    principals {
      type        = "Service"
      identifiers = ["bcm-data-exports.amazonaws.com", "billingreports.amazonaws.com"]
    }

    condition {
      test     = "StringLike"
      variable = "aws:SourceAccount"
      values   = [local.account_id]
    }

    condition {
      test     = "StringLike"
      variable = "aws:SourceArn"
      values = [
        "arn:aws:cur:${local.home_region}:${local.account_id}:definition/*",
        "arn:aws:bcm-data-exports:${local.home_region}:${local.account_id}:export/*",
      ]
    }
  }
}

resource "aws_s3_bucket_policy" "cur" {
  count = local.create_cur_export ? 1 : 0

  region = local.home_region
  bucket = aws_s3_bucket.cur[0].id
  policy = data.aws_iam_policy_document.cur_bucket[0].json

  depends_on = [aws_s3_bucket_public_access_block.cur]
}

resource "aws_bcmdataexports_export" "cur" {
  count = local.create_cur_export ? 1 : 0

  export {
    name        = local.cur_export_name
    description = "CUR 2.0 (Parquet) export for Spike - ${local.account_id}"

    data_query {
      query_statement = replace(trimspace(file("${path.module}/queries/cur2.sql")), "/\\s+/", " ")
      table_configurations = {
        COST_AND_USAGE_REPORT = {
          TIME_GRANULARITY                   = "HOURLY"
          INCLUDE_RESOURCES                  = "TRUE"
          INCLUDE_CAPACITY_RESERVATION_DATA  = "TRUE"
          INCLUDE_IAM_PRINCIPAL_DATA         = "TRUE"
          INCLUDE_SPLIT_COST_ALLOCATION_DATA = "TRUE"
        }
      }
    }

    destination_configurations {
      s3_destination {
        s3_bucket = aws_s3_bucket.cur[0].id
        s3_prefix = local.cur_prefix
        s3_region = local.home_region

        s3_output_configurations {
          format      = "PARQUET"
          compression = "PARQUET"
          output_type = "CUSTOM"
          overwrite   = "OVERWRITE_REPORT"
        }
      }
    }

    refresh_cadence {
      frequency = "SYNCHRONOUS"
    }
  }

  tags = local.tags

  depends_on = [
    aws_s3_bucket_policy.cur,
    aws_s3_bucket_server_side_encryption_configuration.cur,
    aws_s3_bucket_versioning.cur,
  ]
}
